<?php
/**
 * Team Member Addon Settings
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$params = array(
	array(
		'type'       => 'attach_image',
		'heading'    => __( 'Photo', 'classic-addons' ),
		'param_name' => 'image',
		'group'      => 'General',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Image Size', 'classic-addons' ),
		'param_name' => 'img_size',
		'group'      => 'General',
		'value'      => function_exists( 'cawpb_get_image_sizes' ) ? cawpb_get_image_sizes() : array( 'Default' => '' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Name', 'classic-addons' ),
		'param_name' => 'name',
		'group'      => 'General',
		'value'      => __( 'John Doe', 'classic-addons' ),
		'admin_label' => true,
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Designation', 'classic-addons' ),
		'param_name' => 'designation',
		'group'      => 'General',
		'value'      => __( 'Designer', 'classic-addons' ),
	),
	array(
		'type'       => 'textarea',
		'heading'    => __( 'Bio', 'classic-addons' ),
		'param_name' => 'bio',
		'group'      => 'General',
	),
	array(
		'type'       => 'vc_link',
		'heading'    => __( 'Profile Link', 'classic-addons' ),
		'param_name' => 'attach_link',
		'group'      => 'General',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Style', 'classic-addons' ),
		'param_name' => 'style',
		'group'      => 'Design',
		'value'      => array(
			__( 'Classic', 'classic-addons' ) => 'classic',
			__( 'Card', 'classic-addons' )    => 'card',
			__( 'Minimal', 'classic-addons' ) => 'minimal',
			__( 'Overlay (socials on image)', 'classic-addons' ) => 'overlay',
		),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Image Shape', 'classic-addons' ),
		'param_name' => 'img_shape',
		'group'      => 'Design',
		'value'      => array(
			__( 'Rounded', 'classic-addons' ) => 'rounded',
			__( 'Square', 'classic-addons' )  => 'square',
			__( 'Circle', 'classic-addons' )  => 'circle',
		),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Alignment', 'classic-addons' ),
		'param_name' => 'alignment',
		'group'      => 'Design',
		'value'      => array(
			__( 'Center', 'classic-addons' ) => 'center',
			__( 'Left', 'classic-addons' )   => 'left',
			__( 'Right', 'classic-addons' )  => 'right',
		),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Hover Effect', 'classic-addons' ),
		'param_name' => 'hover_effect',
		'group'      => 'Design',
		'value'      => array(
			__( 'None', 'classic-addons' )   => 'none',
			__( 'Lift', 'classic-addons' )   => 'lift',
			__( 'Zoom Image', 'classic-addons' ) => 'zoom',
			__( 'Grayscale', 'classic-addons' ) => 'grayscale',
			__( 'Tilt', 'classic-addons' )   => 'tilt',
		),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Card Shadow', 'classic-addons' ),
		'param_name' => 'shadow',
		'group'      => 'Design',
		'value'      => array(
			__( 'Light', 'classic-addons' )  => 'light',
			__( 'None', 'classic-addons' )   => 'none',
			__( 'Medium', 'classic-addons' ) => 'medium',
			__( 'Strong', 'classic-addons' ) => 'strong',
		),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Background Color', 'classic-addons' ),
		'param_name' => 'team_bg_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Border Color', 'classic-addons' ),
		'param_name' => 'border_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Name Color', 'classic-addons' ),
		'param_name' => 'name_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Designation Color', 'classic-addons' ),
		'param_name' => 'designation_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Bio Color', 'classic-addons' ),
		'param_name' => 'bio_color',
		'group'      => 'Colors',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Border Width', 'classic-addons' ),
		'param_name' => 'border_width',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Border Radius', 'classic-addons' ),
		'param_name' => 'border_radius',
		'group'      => 'Typography',
		'value'      => '8px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Body Padding', 'classic-addons' ),
		'param_name' => 'padding',
		'group'      => 'Typography',
		'description' => __( 'e.g. 20px', 'classic-addons' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Name Font Size', 'classic-addons' ),
		'param_name' => 'name_font_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Designation Font Size', 'classic-addons' ),
		'param_name' => 'desig_font_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'param_group',
		'heading'    => __( 'Social Profiles', 'classic-addons' ),
		'param_name' => 'social_items',
		'group'      => 'Social',
		'params'     => array(
			array(
				'type'       => 'iconpicker',
				'heading'    => __( 'Icon', 'classic-addons' ),
				'param_name' => 'icon',
				'value'      => 'fa-brands fa-facebook-f',
				'settings'   => array(
					'emptyIcon'    => false,
					'iconsPerPage' => 500,
				),
			),
			array(
				'type'        => 'textfield',
				'heading'     => __( 'URL', 'classic-addons' ),
				'param_name'  => 'url',
				'admin_label' => true,
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Accessible Label', 'classic-addons' ),
				'param_name' => 'label',
			),
		),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Social Icon Style', 'classic-addons' ),
		'param_name' => 'social_style',
		'group'      => 'Social',
		'value'      => array(
			__( 'Filled Circle', 'classic-addons' )  => 'filled',
			__( 'Outlined Circle', 'classic-addons' )=> 'outlined',
			__( 'Square', 'classic-addons' )         => 'square',
			__( 'Flat (no background)', 'classic-addons' ) => 'flat',
		),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Social Icon Size', 'classic-addons' ),
		'param_name' => 'social_size',
		'group'      => 'Social',
		'value'      => '36px',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Social Icon Color', 'classic-addons' ),
		'param_name' => 'social_color',
		'group'      => 'Social',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Social Icon Background', 'classic-addons' ),
		'param_name' => 'social_bg',
		'group'      => 'Social',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Social Hover Color', 'classic-addons' ),
		'param_name' => 'social_hover_color',
		'group'      => 'Social',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Social Hover Background', 'classic-addons' ),
		'param_name' => 'social_hover_bg',
		'group'      => 'Social',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
);
