<?php
/**
 * Progress Bar Addon Settings
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$cawpb_params = array(
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Label', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'label',
		'group'      => 'General',
		'value'      => __( 'Skill', 'classic-addons-wpbakery-page-builder' ),
		'admin_label' => true,
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Value', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'value',
		'group'      => 'General',
		'value'      => '75',
		'edit_field_class' => 'vc_col-xs-4 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Max Value', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'max',
		'group'      => 'General',
		'value'      => '100',
		'edit_field_class' => 'vc_col-xs-4 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Unit Suffix', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'unit',
		'group'      => 'General',
		'value'      => '%',
		'edit_field_class' => 'vc_col-xs-4 vc_column',
		'description' => __( 'E.g. %, px, pts (leave empty for none).', 'classic-addons-wpbakery-page-builder' ),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Style', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'style',
		'group'      => 'General',
		'value'      => array(
			__( 'Default', 'classic-addons-wpbakery-page-builder' )    => 'default',
			__( 'Rounded', 'classic-addons-wpbakery-page-builder' )    => 'rounded',
			__( 'Thin', 'classic-addons-wpbakery-page-builder' )       => 'thin',
			__( 'Thick', 'classic-addons-wpbakery-page-builder' )      => 'thick',
			__( 'Dark', 'classic-addons-wpbakery-page-builder' )       => 'dark',
		),
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Label', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'show_label',
		'group'      => 'General',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
		'std'        => 'yes',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Value', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'show_value',
		'group'      => 'General',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
		'std'        => 'yes',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Value Position', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'value_position',
		'group'      => 'General',
		'value'      => array(
			__( 'Inline (Inside Bar)', 'classic-addons-wpbakery-page-builder' ) => 'inline',
			__( 'Top (Next to Label)', 'classic-addons-wpbakery-page-builder' ) => 'top',
		),
		'dependency' => array( 'element' => 'show_value', 'value' => 'yes' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Bar Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'bar_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Track Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'bar_bg_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Label Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'label_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Value Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'value_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Gradient Bar', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'bar_gradient',
		'group'      => 'Colors',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Gradient From', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'gradient_from',
		'group'      => 'Colors',
		'dependency' => array( 'element' => 'bar_gradient', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Gradient To', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'gradient_to',
		'group'      => 'Colors',
		'dependency' => array( 'element' => 'bar_gradient', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Bar Height', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'bar_height',
		'group'      => 'Typography',
		'value'      => '10px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Border Radius', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'border_radius',
		'group'      => 'Typography',
		'value'      => '999px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Label Font Size', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'label_font_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Value Font Size', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'value_font_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Animate on Scroll', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'animation',
		'group'      => 'Animation',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
		'std'        => 'yes',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Animation Duration (ms)', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'animation_speed',
		'group'      => 'Animation',
		'value'      => '1500',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Striped Bar', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'striped',
		'group'      => 'Animation',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Animated Stripes', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'animated_stripes',
		'group'      => 'Animation',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
		'dependency' => array( 'element' => 'striped', 'value' => 'yes' ),
	),
);
