<?php
/**
 * Pricing Table Addon Settings
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$cawpb_params = array(
	// Style preset
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Style Preset', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'style',
		'group'      => 'General',
		'value'      => array(
			__( 'Classic', 'classic-addons-wpbakery-page-builder' ) => 'classic',
			__( 'Minimal', 'classic-addons-wpbakery-page-builder' ) => 'minimal',
			__( 'Modern', 'classic-addons-wpbakery-page-builder' )  => 'modern',
		),
		'std' => 'classic',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Highlight (Featured Table)', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'is_featured',
		'group'      => 'General',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
		'description' => __( 'Adds accent border and a slight scale-up to make this table stand out.', 'classic-addons-wpbakery-page-builder' ),
	),

	// Header group
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Plan Title', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'title',
		'group'      => 'Header',
		'value'      => __( 'Basic', 'classic-addons-wpbakery-page-builder' ),
		'admin_label' => true,
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Title Tag', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'title_tag',
		'group'      => 'Header',
		'value'      => array( 'H1' => 'h1', 'H2' => 'h2', 'H3' => 'h3', 'H4' => 'h4', 'H5' => 'h5', 'H6' => 'h6', 'DIV' => 'div', 'SPAN' => 'span' ),
		'std'        => 'h3',
	),
	array(
		'type'       => 'textarea',
		'heading'    => __( 'Subtitle / Description', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'subtitle',
		'group'      => 'Header',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Header Media', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'media_type',
		'group'      => 'Header',
		'value'      => array(
			__( 'None', 'classic-addons-wpbakery-page-builder' )  => 'none',
			__( 'Icon', 'classic-addons-wpbakery-page-builder' )  => 'icon',
			__( 'Image', 'classic-addons-wpbakery-page-builder' ) => 'image',
		),
		'std' => 'none',
	),
	array(
		'type'       => 'iconpicker',
		'heading'    => __( 'Icon', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'header_icon',
		'group'      => 'Header',
		'value'      => 'fas fa-star',
		'settings'   => array( 'emptyIcon' => false, 'iconsPerPage' => 500 ),
		'dependency' => array( 'element' => 'media_type', 'value' => 'icon' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Icon Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'header_icon_color',
		'group'      => 'Header',
		'dependency' => array( 'element' => 'media_type', 'value' => 'icon' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Icon Size', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'header_icon_size',
		'group'      => 'Header',
		'value'      => '40px',
		'dependency' => array( 'element' => 'media_type', 'value' => 'icon' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'attach_image',
		'heading'    => __( 'Image', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'header_image',
		'group'      => 'Header',
		'dependency' => array( 'element' => 'media_type', 'value' => 'image' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Header Background', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'header_bg',
		'group'      => 'Header',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Title Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'title_color',
		'group'      => 'Header',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Subtitle Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'subtitle_color',
		'group'      => 'Header',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Title Font Size', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'title_font_size',
		'group'      => 'Header',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Subtitle Font Size', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'subtitle_font_size',
		'group'      => 'Header',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Pricing group
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Currency Symbol', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'currency',
		'group'      => 'Pricing',
		'value'      => '$',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Currency Position', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'currency_position',
		'group'      => 'Pricing',
		'value'      => array(
			__( 'Before', 'classic-addons-wpbakery-page-builder' ) => 'before',
			__( 'After', 'classic-addons-wpbakery-page-builder' )  => 'after',
		),
		'std' => 'before',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Price', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'price',
		'group'      => 'Pricing',
		'value'      => '29',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Original / Old Price', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'old_price',
		'group'      => 'Pricing',
		'description' => __( 'Shown with strike-through when filled.', 'classic-addons-wpbakery-page-builder' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Period Text', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'period',
		'group'      => 'Pricing',
		'value'      => __( '/mo', 'classic-addons-wpbakery-page-builder' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'On Sale', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'on_sale',
		'group'      => 'Pricing',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Sale Label Text', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'sale_text',
		'group'      => 'Pricing',
		'value'      => __( 'Sale', 'classic-addons-wpbakery-page-builder' ),
		'dependency' => array( 'element' => 'on_sale', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Price Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'price_color',
		'group'      => 'Pricing',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Currency Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'currency_color',
		'group'      => 'Pricing',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Period Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'period_color',
		'group'      => 'Pricing',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Price Font Size', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'price_font_size',
		'group'      => 'Pricing',
		'value'      => '48px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Features group
	array(
		'type'       => 'param_group',
		'heading'    => __( 'Features', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'features',
		'group'      => 'Features',
		'params'     => array(
			array(
				'type'        => 'textfield',
				'heading'     => __( 'Feature Text', 'classic-addons-wpbakery-page-builder' ),
				'param_name'  => 'text',
				'admin_label' => true,
			),
			array(
				'type'       => 'iconpicker',
				'heading'    => __( 'Icon', 'classic-addons-wpbakery-page-builder' ),
				'param_name' => 'icon',
				'value'      => 'fas fa-check',
				'settings'   => array( 'emptyIcon' => false, 'iconsPerPage' => 500 ),
			),
			array(
				'type'       => 'colorpicker',
				'heading'    => __( 'Icon Color', 'classic-addons-wpbakery-page-builder' ),
				'param_name' => 'icon_color',
			),
			array(
				'type'       => 'checkbox',
				'heading'    => __( 'Excluded?', 'classic-addons-wpbakery-page-builder' ),
				'param_name' => 'excluded',
				'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
				'description' => __( 'Renders with a cross icon and strike-through.', 'classic-addons-wpbakery-page-builder' ),
			),
		),
		'value' => urlencode( wp_json_encode( array(
			array( 'text' => 'Unlimited Projects',   'icon' => 'fas fa-check', 'icon_color' => '', 'excluded' => '' ),
			array( 'text' => '24/7 Support',          'icon' => 'fas fa-check', 'icon_color' => '', 'excluded' => '' ),
			array( 'text' => 'Advanced Analytics',    'icon' => 'fas fa-check', 'icon_color' => '', 'excluded' => 'yes' ),
		) ) ),
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Divider Between Features', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'feature_divider',
		'group'      => 'Features',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Feature Text Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'feature_text_color',
		'group'      => 'Features',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Divider Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'divider_color',
		'group'      => 'Features',
		'dependency' => array( 'element' => 'feature_divider', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Footer group
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Button Text', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'button_text',
		'group'      => 'Footer',
		'value'      => __( 'Choose Plan', 'classic-addons-wpbakery-page-builder' ),
	),
	array(
		'type'       => 'vc_link',
		'heading'    => __( 'Button Link', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'button_link',
		'group'      => 'Footer',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Info Text (under button)', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'footer_info',
		'group'      => 'Footer',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Button Background', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'btn_bg',
		'group'      => 'Footer',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Button Text Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'btn_color',
		'group'      => 'Footer',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Button Hover Background', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'btn_bg_hover',
		'group'      => 'Footer',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Button Hover Text', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'btn_color_hover',
		'group'      => 'Footer',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Ribbon group
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Enable Ribbon', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'ribbon_enable',
		'group'      => 'Ribbon',
		'value'      => array( __( 'Yes', 'classic-addons-wpbakery-page-builder' ) => 'yes' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Ribbon Text', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'ribbon_text',
		'group'      => 'Ribbon',
		'value'      => __( 'Popular', 'classic-addons-wpbakery-page-builder' ),
		'dependency' => array( 'element' => 'ribbon_enable', 'value' => 'yes' ),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Ribbon Style', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'ribbon_style',
		'group'      => 'Ribbon',
		'value'      => array(
			__( 'Corner', 'classic-addons-wpbakery-page-builder' ) => 'corner',
			__( 'Flag', 'classic-addons-wpbakery-page-builder' )   => 'flag',
			__( 'Stripe', 'classic-addons-wpbakery-page-builder' ) => 'stripe',
		),
		'std'        => 'corner',
		'dependency' => array( 'element' => 'ribbon_enable', 'value' => 'yes' ),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Ribbon Position', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'ribbon_position',
		'group'      => 'Ribbon',
		'value'      => array(
			__( 'Top Right', 'classic-addons-wpbakery-page-builder' ) => 'top-right',
			__( 'Top Left', 'classic-addons-wpbakery-page-builder' )  => 'top-left',
		),
		'std'        => 'top-right',
		'dependency' => array( 'element' => 'ribbon_enable', 'value' => 'yes' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Ribbon Background', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'ribbon_bg',
		'group'      => 'Ribbon',
		'dependency' => array( 'element' => 'ribbon_enable', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Ribbon Text Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'ribbon_color',
		'group'      => 'Ribbon',
		'dependency' => array( 'element' => 'ribbon_enable', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Box style group
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Box Background', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'box_bg',
		'group'      => 'Box Style',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Box Border Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'box_border_color',
		'group'      => 'Box Style',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Box Border Width', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'box_border_width',
		'group'      => 'Box Style',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Box Border Radius', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'box_radius',
		'group'      => 'Box Style',
		'value'      => '10px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Box Shadow', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'box_shadow',
		'group'      => 'Box Style',
		'value'      => array(
			__( 'None', 'classic-addons-wpbakery-page-builder' )   => 'none',
			__( 'Light', 'classic-addons-wpbakery-page-builder' )  => 'light',
			__( 'Medium', 'classic-addons-wpbakery-page-builder' ) => 'medium',
			__( 'Heavy', 'classic-addons-wpbakery-page-builder' )  => 'heavy',
		),
		'std' => 'light',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Featured Accent Color', 'classic-addons-wpbakery-page-builder' ),
		'param_name' => 'featured_accent',
		'group'      => 'Box Style',
		'dependency' => array( 'element' => 'is_featured', 'value' => 'yes' ),
		'description' => __( 'Border + button accent for the highlighted state.', 'classic-addons-wpbakery-page-builder' ),
	),
);
