<?php
/**
 * Countdown Timer Addon Settings
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$params = array(
	array(
		'type'        => 'textfield',
		'heading'     => __( 'Target Date & Time', 'classic-addons' ),
		'param_name'  => 'target_datetime',
		'group'       => 'General',
		'value'       => '',
		'admin_label' => true,
		'description' => __( 'Format: YYYY-MM-DD HH:MM:SS (24-hour). Example: 2026-12-31 23:59:00', 'classic-addons' ),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Timezone', 'classic-addons' ),
		'param_name' => 'timezone_mode',
		'group'      => 'General',
		'value'      => array(
			__( 'Site timezone (WordPress setting)', 'classic-addons' ) => 'site',
			__( 'Visitor local timezone', 'classic-addons' )            => 'local',
			__( 'UTC', 'classic-addons' )                               => 'utc',
		),
		'std'         => 'site',
		'description' => __( 'How the target date is interpreted.', 'classic-addons' ),
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Style Preset', 'classic-addons' ),
		'param_name' => 'style',
		'group'      => 'General',
		'value'      => array(
			__( 'Boxed', 'classic-addons' )           => 'boxed',
			__( 'Circle', 'classic-addons' )          => 'circle',
			__( 'Minimal / Inline', 'classic-addons' ) => 'minimal',
		),
		'std' => 'boxed',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Alignment', 'classic-addons' ),
		'param_name' => 'alignment',
		'group'      => 'General',
		'value'      => array(
			__( 'Center', 'classic-addons' ) => 'center',
			__( 'Left', 'classic-addons' )   => 'left',
			__( 'Right', 'classic-addons' )  => 'right',
		),
		'std' => 'center',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Separator Between Units', 'classic-addons' ),
		'param_name' => 'show_separator',
		'group'      => 'General',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
	),

	// Units group
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Days', 'classic-addons' ),
		'param_name' => 'show_days',
		'group'      => 'Units',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
		'std'        => 'yes',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Days Label', 'classic-addons' ),
		'param_name' => 'label_days',
		'group'      => 'Units',
		'value'      => __( 'Days', 'classic-addons' ),
		'dependency' => array( 'element' => 'show_days', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Hours', 'classic-addons' ),
		'param_name' => 'show_hours',
		'group'      => 'Units',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
		'std'        => 'yes',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Hours Label', 'classic-addons' ),
		'param_name' => 'label_hours',
		'group'      => 'Units',
		'value'      => __( 'Hours', 'classic-addons' ),
		'dependency' => array( 'element' => 'show_hours', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Minutes', 'classic-addons' ),
		'param_name' => 'show_minutes',
		'group'      => 'Units',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
		'std'        => 'yes',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Minutes Label', 'classic-addons' ),
		'param_name' => 'label_minutes',
		'group'      => 'Units',
		'value'      => __( 'Minutes', 'classic-addons' ),
		'dependency' => array( 'element' => 'show_minutes', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Seconds', 'classic-addons' ),
		'param_name' => 'show_seconds',
		'group'      => 'Units',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
		'std'        => 'yes',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Seconds Label', 'classic-addons' ),
		'param_name' => 'label_seconds',
		'group'      => 'Units',
		'value'      => __( 'Seconds', 'classic-addons' ),
		'dependency' => array( 'element' => 'show_seconds', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Expiry group
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'On Expiry', 'classic-addons' ),
		'param_name' => 'expiry_action',
		'group'      => 'On Expiry',
		'value'      => array(
			__( 'Show a message', 'classic-addons' ) => 'message',
			__( 'Hide the timer', 'classic-addons' ) => 'hide',
		),
		'std' => 'message',
	),
	array(
		'type'       => 'textarea',
		'heading'    => __( 'Expiry Message', 'classic-addons' ),
		'param_name' => 'expiry_message',
		'group'      => 'On Expiry',
		'value'      => __( 'This offer has expired.', 'classic-addons' ),
		'dependency' => array( 'element' => 'expiry_action', 'value' => 'message' ),
	),

	// Colors group
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Number Color', 'classic-addons' ),
		'param_name' => 'number_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Label Color', 'classic-addons' ),
		'param_name' => 'label_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Box Background', 'classic-addons' ),
		'param_name' => 'box_bg',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'Applies to Boxed / Circle styles.', 'classic-addons' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Box Border Color', 'classic-addons' ),
		'param_name' => 'box_border_color',
		'group'      => 'Colors',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Separator Color', 'classic-addons' ),
		'param_name' => 'separator_color',
		'group'      => 'Colors',
		'dependency' => array( 'element' => 'show_separator', 'value' => 'yes' ),
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),

	// Typography & spacing
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Number Font Size', 'classic-addons' ),
		'param_name' => 'number_font_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'e.g. 48px, 3rem', 'classic-addons' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Number Font Weight', 'classic-addons' ),
		'param_name' => 'number_font_weight',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'e.g. 400, 600, 700', 'classic-addons' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Label Font Size', 'classic-addons' ),
		'param_name' => 'label_font_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Label Font Weight', 'classic-addons' ),
		'param_name' => 'label_font_weight',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Box Size', 'classic-addons' ),
		'param_name' => 'box_size',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'Min width/height per unit. e.g. 90px', 'classic-addons' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Unit Gap', 'classic-addons' ),
		'param_name' => 'unit_gap',
		'group'      => 'Typography',
		'value'      => '16px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'Space between units. e.g. 16px', 'classic-addons' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Border Radius', 'classic-addons' ),
		'param_name' => 'box_radius',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'e.g. 8px (Boxed style)', 'classic-addons' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Border Width', 'classic-addons' ),
		'param_name' => 'box_border_width',
		'group'      => 'Typography',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'e.g. 1px', 'classic-addons' ),
	),
);
