<?php
/**
 * Image Hotspots Addon Settings
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$params = array(
	// Image
	array(
		'type'       => 'attach_image',
		'heading'    => __( 'Base Image', 'classic-addons' ),
		'param_name' => 'image',
		'group'      => 'General',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Image Size', 'classic-addons' ),
		'param_name' => 'img_size',
		'group'      => 'General',
		'value'      => function_exists( 'cawpb_get_image_sizes' ) ? cawpb_get_image_sizes() : array( 'Default' => '' ),
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Image Overlay Color', 'classic-addons' ),
		'param_name' => 'overlay_color',
		'group'      => 'General',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Overlay Opacity (0-1)', 'classic-addons' ),
		'param_name' => 'overlay_opacity',
		'group'      => 'General',
		'value'      => '0',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
		'description' => __( 'e.g. 0.3', 'classic-addons' ),
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Max Width', 'classic-addons' ),
		'param_name' => 'max_width',
		'group'      => 'General',
		'description' => __( 'e.g. 800px. Leave empty for full width.', 'classic-addons' ),
	),

	// Markers (param_group)
	array(
		'type'       => 'param_group',
		'heading'    => __( 'Markers', 'classic-addons' ),
		'param_name' => 'markers',
		'group'      => 'Markers',
		'params'     => array(
			array(
				'type'        => 'textfield',
				'heading'     => __( 'Horizontal Position (%)', 'classic-addons' ),
				'param_name'  => 'pos_x',
				'value'       => '50',
				'admin_label' => true,
				'edit_field_class' => 'vc_col-xs-6 vc_column',
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Vertical Position (%)', 'classic-addons' ),
				'param_name' => 'pos_y',
				'value'      => '50',
				'edit_field_class' => 'vc_col-xs-6 vc_column',
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Marker Type', 'classic-addons' ),
				'param_name' => 'marker_type',
				'value'      => array(
					__( 'Icon', 'classic-addons' )  => 'icon',
					__( 'Text', 'classic-addons' )  => 'text',
					__( 'Image', 'classic-addons' ) => 'image',
				),
				'std' => 'icon',
			),
			array(
				'type'       => 'iconpicker',
				'heading'    => __( 'Icon', 'classic-addons' ),
				'param_name' => 'icon',
				'value'      => 'fas fa-plus',
				'settings'   => array( 'emptyIcon' => false, 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'marker_type', 'value' => 'icon' ),
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Text', 'classic-addons' ),
				'param_name' => 'text',
				'dependency' => array( 'element' => 'marker_type', 'value' => 'text' ),
			),
			array(
				'type'       => 'attach_image',
				'heading'    => __( 'Image', 'classic-addons' ),
				'param_name' => 'image',
				'dependency' => array( 'element' => 'marker_type', 'value' => 'image' ),
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Trigger', 'classic-addons' ),
				'param_name' => 'trigger',
				'value'      => array(
					__( 'Hover', 'classic-addons' ) => 'hover',
					__( 'Click', 'classic-addons' ) => 'click',
				),
				'std' => 'hover',
			),
			array(
				'type'       => 'dropdown',
				'heading'    => __( 'Tooltip Position', 'classic-addons' ),
				'param_name' => 'tooltip_pos',
				'value'      => array(
					__( 'Top', 'classic-addons' )    => 'top',
					__( 'Bottom', 'classic-addons' ) => 'bottom',
					__( 'Left', 'classic-addons' )   => 'left',
					__( 'Right', 'classic-addons' )  => 'right',
				),
				'std' => 'top',
			),
			array(
				'type'       => 'textfield',
				'heading'    => __( 'Tooltip Heading', 'classic-addons' ),
				'param_name' => 'tooltip_heading',
			),
			array(
				'type'       => 'textarea_html',
				'heading'    => __( 'Tooltip Description', 'classic-addons' ),
				'param_name' => 'tooltip_desc',
			),
			array(
				'type'       => 'vc_link',
				'heading'    => __( 'Marker Link (optional)', 'classic-addons' ),
				'param_name' => 'link',
			),
			array(
				'type'       => 'checkbox',
				'heading'    => __( 'Open by Default', 'classic-addons' ),
				'param_name' => 'open_default',
				'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
			),
		),
		'value' => urlencode( wp_json_encode( array(
			array(
				'pos_x' => '30', 'pos_y' => '40', 'marker_type' => 'icon',
				'icon'  => 'fas fa-plus', 'trigger' => 'hover', 'tooltip_pos' => 'top',
				'tooltip_heading' => 'Marker 1', 'tooltip_desc' => 'Tooltip text here.', 'open_default' => '',
			),
			array(
				'pos_x' => '70', 'pos_y' => '60', 'marker_type' => 'icon',
				'icon'  => 'fas fa-plus', 'trigger' => 'click', 'tooltip_pos' => 'bottom',
				'tooltip_heading' => 'Marker 2', 'tooltip_desc' => 'Click to open.', 'open_default' => '',
			),
		) ) ),
	),

	// Global Marker Style
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Marker Size', 'classic-addons' ),
		'param_name' => 'marker_size',
		'group'      => 'Marker Style',
		'value'      => '32px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Marker Icon Size', 'classic-addons' ),
		'param_name' => 'marker_icon_size',
		'group'      => 'Marker Style',
		'value'      => '14px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Marker Color (icon/text)', 'classic-addons' ),
		'param_name' => 'marker_color',
		'group'      => 'Marker Style',
		'value'      => '#ffffff',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Marker Background', 'classic-addons' ),
		'param_name' => 'marker_bg',
		'group'      => 'Marker Style',
		'value'      => '#0073aa',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Marker Border Color', 'classic-addons' ),
		'param_name' => 'marker_border_color',
		'group'      => 'Marker Style',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Marker Border Width', 'classic-addons' ),
		'param_name' => 'marker_border_width',
		'group'      => 'Marker Style',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Marker Border Radius', 'classic-addons' ),
		'param_name' => 'marker_radius',
		'group'      => 'Marker Style',
		'value'      => '50%',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Marker Shadow', 'classic-addons' ),
		'param_name' => 'marker_shadow',
		'group'      => 'Marker Style',
		'value'      => array(
			__( 'None', 'classic-addons' )   => 'none',
			__( 'Light', 'classic-addons' )  => 'light',
			__( 'Medium', 'classic-addons' ) => 'medium',
			__( 'Heavy', 'classic-addons' )  => 'heavy',
		),
		'std' => 'light',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Pulse / Radar Animation', 'classic-addons' ),
		'param_name' => 'marker_pulse',
		'group'      => 'Marker Style',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
		'std'        => 'yes',
	),

	// Global Tooltip Style
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Tooltip Background', 'classic-addons' ),
		'param_name' => 'tip_bg',
		'group'      => 'Tooltip Style',
		'value'      => '#222222',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'colorpicker',
		'heading'    => __( 'Tooltip Text Color', 'classic-addons' ),
		'param_name' => 'tip_color',
		'group'      => 'Tooltip Style',
		'value'      => '#ffffff',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Tooltip Font Size', 'classic-addons' ),
		'param_name' => 'tip_font_size',
		'group'      => 'Tooltip Style',
		'value'      => '13px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Heading Font Size', 'classic-addons' ),
		'param_name' => 'tip_heading_size',
		'group'      => 'Tooltip Style',
		'value'      => '15px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Min Width', 'classic-addons' ),
		'param_name' => 'tip_min_width',
		'group'      => 'Tooltip Style',
		'value'      => '160px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Max Width', 'classic-addons' ),
		'param_name' => 'tip_max_width',
		'group'      => 'Tooltip Style',
		'value'      => '260px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Padding', 'classic-addons' ),
		'param_name' => 'tip_padding',
		'group'      => 'Tooltip Style',
		'value'      => '10px 14px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'textfield',
		'heading'    => __( 'Border Radius', 'classic-addons' ),
		'param_name' => 'tip_radius',
		'group'      => 'Tooltip Style',
		'value'      => '6px',
		'edit_field_class' => 'vc_col-xs-6 vc_column',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Tooltip Shadow', 'classic-addons' ),
		'param_name' => 'tip_shadow',
		'group'      => 'Tooltip Style',
		'value'      => array(
			__( 'None', 'classic-addons' )   => 'none',
			__( 'Light', 'classic-addons' )  => 'light',
			__( 'Medium', 'classic-addons' ) => 'medium',
			__( 'Heavy', 'classic-addons' )  => 'heavy',
		),
		'std' => 'medium',
	),
	array(
		'type'       => 'checkbox',
		'heading'    => __( 'Show Arrow', 'classic-addons' ),
		'param_name' => 'tip_arrow',
		'group'      => 'Tooltip Style',
		'value'      => array( __( 'Yes', 'classic-addons' ) => 'yes' ),
		'std'        => 'yes',
	),
	array(
		'type'       => 'dropdown',
		'heading'    => __( 'Open Animation', 'classic-addons' ),
		'param_name' => 'tip_animation',
		'group'      => 'Tooltip Style',
		'value'      => array(
			__( 'Fade', 'classic-addons' )  => 'fade',
			__( 'Slide', 'classic-addons' ) => 'slide',
			__( 'None', 'classic-addons' )  => 'none',
		),
		'std' => 'fade',
	),
);
